### ISSUE TITLE
More frequent releases of haystack-experimental

### ISSUE THREAD

**Issue by RocketRider** [deepset-ai/haystack-experimental#149]
Would it make sense to publish haystack-experimental automatically with a nightly build? As it is experimental it makes no sense to use a release that is 3 Months old. Or please publish releases more frequently.

**Comment by julian-risch** [comment]
Hello @RocketRider and thank you for your feedback! I agree we should release haystack-experimental more frequently. Probably not nightly but at least every four weeks. I'll discuss with the team. 
In the meantime, you can simply install via `!pip install -U git+https://github.com/deepset-ai/haystack-experimental`

**Comment by julian-risch** [comment]
We released 0.4.0 of haystack-experimental last week: https://github.com/deepset-ai/haystack-experimental/releases/tag/v0.4.0 and we will release haystack-experimental more frequently.
