### ISSUE TITLE
`ChatMessageRetriever` flexibility issues

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-experimental#72]
While preparing a notebook on Tools, I needed some form of short-term memory of the conversation.
I tried to use `ChatMessageStore`, `ChatMessageWriter`, and`ChatMessageRetriever`.

Unfortunately, I have encountered some **roadblocks with the `ChatMessageRetriever`**.
You can find my experiments [in this notebook](https://colab.research.google.com/drive/1PKVO3Gemacl_7EcDRGT0O1i9Cq5tczUF?usp=sharing).

---

Main problems I have encountered:
`ChatMessageRetriever` has no input sockets
- cannot receive any input from other components
- cannot be placed in a conditional branch
- must be placed at the beginning of a Pipeline
- since it does not need inputs, it always runs

I am aware of the ongoing work on the ChatMessageRetriever (see deepset-ai/haystack#8258), but my impression is that most of these issues will remain.

 Given that my use case is not very exotic, I think it would be beneficial to reflect on how to improve and make this experimental component more flexible.

**Comment by shadeMe** [comment]
Moved to the discussion.
